<?php

declare(strict_types=1);

namespace App\Service\ImageStrategy;

use App\Constants\Code;
use App\Contract\ImageStrategyInterface;
use App\Dto\ImageResult;
use App\Exception\BusinessException;
use App\Service\OssUploader;
use GuzzleHttp\Exception\GuzzleException;
use Hyperf\Contract\ConfigInterface;
use Hyperf\Contract\StdoutLoggerInterface;
use Throwable;

/**
 * Nano Banana 策略（DashScope 万相文生图）。
 *
 * 流程：
 *   1. POST /services/aigc/text2image/image-synthesis   header X-DashScope-Async: enable
 *      → { output: { task_id, task_status: PENDING } }
 *   2. 轮询 GET /tasks/{task_id} 直到 task_status = SUCCEEDED / FAILED
 *   3. 成功时解析 results[0].url → 下载上传 OSS
 *
 * 注意：万相返回的临时 URL 通常 24h 失效，生产必须上传 OSS。
 *       OSS 未启用时会留在临时 URL（日志警告）。
 */
class NanoBananaStrategy extends AbstractImageStrategy implements ImageStrategyInterface
{
    private bool $enabled;
    private string $apiKey;
    private string $model;
    private string $submitEndpoint;
    private string $taskEndpoint;
    private string $size;
    private int $pollInterval;
    private int $maxPoll;

    public function __construct(
        ConfigInterface $config,
        private readonly OssUploader $uploader,
        private readonly StdoutLoggerInterface $logger
    ) {
        $c = (array) $config->get('image.strategies.nanobanana', []);
        $this->enabled = (bool) ($c['enabled'] ?? true);
        $this->model = (string) ($c['model'] ?? 'wanx2.1-t2i-turbo');
        $this->submitEndpoint = (string) ($c['submit_endpoint'] ?? 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text2image/image-synthesis');
        $this->taskEndpoint = rtrim((string) ($c['task_endpoint'] ?? 'https://dashscope.aliyuncs.com/api/v1/tasks'), '/');
        $this->size = (string) ($c['size'] ?? '1024*768');
        $this->pollInterval = (int) ($c['poll_interval'] ?? 2);
        $this->maxPoll = (int) ($c['max_poll'] ?? 15);

        // 复用 DashScope API Key
        $this->apiKey = (string) $config->get('model.providers.dashscope.api_key', '');
    }

    public function getName(): string
    {
        return 'nanobanana';
    }

    public function getLabel(): string
    {
        return 'Nano Banana AI 生图';
    }

    public function isEnabled(): bool
    {
        return $this->enabled && $this->apiKey !== '';
    }

    public function supports(string $type): bool
    {
        return $type === 'nanobanana';
    }

    public function fetch(string $keyword, array $options = []): ImageResult
    {
        if (! $this->isEnabled()) {
            throw new BusinessException(Code::IMAGE_STRATEGY_DISABLED, 'NanoBanana not configured', 500);
        }

        $kw = $this->normalizeKeyword($keyword);
        if ($kw === '') {
            throw new BusinessException(Code::IMAGE_FETCH_FAILED, 'empty keyword', 422);
        }

        try {
            $taskId = $this->submitTask($kw, (string) ($options['context'] ?? ''));
            $imageUrl = $this->pollTask($taskId);
        } catch (BusinessException $e) {
            throw $e;
        } catch (GuzzleException $e) {
            throw new BusinessException(Code::IMAGE_FETCH_FAILED, 'nanobanana request failed: ' . $e->getMessage(), 502, $e);
        } catch (Throwable $e) {
            throw new BusinessException(Code::IMAGE_FETCH_FAILED, 'nanobanana unexpected: ' . $e->getMessage(), 502, $e);
        }

        $finalUrl = $this->uploader->uploadFromUrl($imageUrl, 'jpg');

        return new ImageResult(
            source: 'nanobanana',
            url: $finalUrl,
            originalUrl: $imageUrl,
            alt: "AI生图：{$kw}",
            attribution: 'Generated by Alibaba Wanxiang',
            mime: 'image/jpeg',
        );
    }

    private function submitTask(string $keyword, string $context): string
    {
        $prompt = $context !== ''
            ? "{$keyword}，文章配图，{$context}，高质量，摄影风格"
            : "{$keyword}，文章配图，高质量，摄影风格";

        $res = $this->http(['timeout' => 30])->post($this->submitEndpoint, [
            'headers' => [
                'Authorization' => 'Bearer ' . $this->apiKey,
                'Content-Type' => 'application/json',
                'X-DashScope-Async' => 'enable',
            ],
            'json' => [
                'model' => $this->model,
                'input' => ['prompt' => $prompt],
                'parameters' => ['size' => $this->size, 'n' => 1],
            ],
        ]);

        $data = json_decode((string) $res->getBody(), true);
        $taskId = $data['output']['task_id'] ?? null;

        if (! is_string($taskId) || $taskId === '') {
            throw new BusinessException(
                Code::IMAGE_FETCH_FAILED,
                'no task_id in submit response: ' . json_encode($data, JSON_UNESCAPED_UNICODE),
                502
            );
        }

        $this->logger->debug("[NanoBananaStrategy] task submitted: {$taskId}");
        return $taskId;
    }

    private function pollTask(string $taskId): string
    {
        $client = $this->http(['timeout' => 20]);

        for ($i = 0; $i < $this->maxPoll; $i++) {
            // Hyperf 协程下使用 sleep 自动挂起
            if ($i > 0) {
                sleep($this->pollInterval);
            }

            $res = $client->get("{$this->taskEndpoint}/{$taskId}", [
                'headers' => [
                    'Authorization' => 'Bearer ' . $this->apiKey,
                ],
            ]);
            $data = json_decode((string) $res->getBody(), true);
            $status = (string) ($data['output']['task_status'] ?? 'UNKNOWN');

            if ($status === 'SUCCEEDED') {
                $url = $data['output']['results'][0]['url'] ?? null;
                if (! is_string($url) || $url === '') {
                    throw new BusinessException(Code::IMAGE_FETCH_FAILED, 'no image url in SUCCEEDED task', 502);
                }
                return $url;
            }

            if ($status === 'FAILED' || $status === 'UNKNOWN_ERROR') {
                $reason = (string) ($data['output']['message'] ?? 'task failed');
                throw new BusinessException(Code::IMAGE_FETCH_FAILED, "nanobanana task failed: {$reason}", 502);
            }

            // PENDING / RUNNING 继续轮询
        }

        throw new BusinessException(Code::IMAGE_FETCH_FAILED, "nanobanana poll timeout after {$this->maxPoll} attempts", 504);
    }
}
