<?php

declare(strict_types=1);

namespace App\Service\ImageStrategy;

use App\Constants\Code;
use App\Contract\ImageStrategyInterface;
use App\Dto\ImageResult;
use App\Exception\BusinessException;
use App\Service\ModelProviderService;
use App\Service\OssUploader;
use Hyperf\Contract\ConfigInterface;
use Hyperf\Contract\StdoutLoggerInterface;
use Throwable;

/**
 * SVG 概念示意图策略。
 *
 * 通过 DashScope 生成 SVG 代码 → 清洗 → 上传 OSS（或 inline dataURI）。
 * 失败时抛 BusinessException，由 Factory 降级到 iconify/emoji。
 */
class SvgConceptStrategy extends AbstractImageStrategy implements ImageStrategyInterface
{
    private bool $enabled;
    private string $model;

    public function __construct(
        ConfigInterface $config,
        private readonly ModelProviderService $providers,
        private readonly OssUploader $uploader,
        private readonly StdoutLoggerInterface $logger
    ) {
        $c = (array) $config->get('image.strategies.svg', []);
        $this->enabled = (bool) ($c['enabled'] ?? true);
        $this->model = (string) ($c['model'] ?? 'qwen-plus');
    }

    public function getName(): string
    {
        return 'svg';
    }

    public function getLabel(): string
    {
        return 'SVG 概念示意图';
    }

    public function isEnabled(): bool
    {
        return $this->enabled;
    }

    public function supports(string $type): bool
    {
        return $type === 'svg';
    }

    public function fetch(string $keyword, array $options = []): ImageResult
    {
        if (! $this->isEnabled()) {
            throw new BusinessException(Code::IMAGE_STRATEGY_DISABLED, 'SVG disabled', 500);
        }

        $kw = $this->normalizeKeyword($keyword);
        if ($kw === '') {
            throw new BusinessException(Code::IMAGE_FETCH_FAILED, 'empty keyword', 422);
        }

        $context = (string) ($options['context'] ?? '');
        $prompt = $this->buildPrompt($kw, $context);

        try {
            $raw = $this->providers->driver()->chat(
                $prompt,
                [
                    ['role' => 'system', 'content' => '你是一个SVG图形设计师，只输出纯 SVG 代码，不解释。'],
                    ['role' => 'user', 'content' => $prompt],
                ],
                ['temperature' => 0.3, 'max_tokens' => 1500, 'model' => $this->model]
            );
        } catch (Throwable $e) {
            throw new BusinessException(Code::IMAGE_FETCH_FAILED, 'SVG provider error: ' . $e->getMessage(), 502, $e);
        }

        $svg = $this->extractSvg($raw);
        if ($svg === '') {
            throw new BusinessException(Code::IMAGE_FETCH_FAILED, 'no valid <svg> in model output', 502);
        }

        // OSS 可用则上传，否则返回 data URI
        if ($this->uploader->isEnabled()) {
            try {
                $url = $this->uploader->uploadFromContent($svg, 'svg', 'image/svg+xml');
            } catch (Throwable $e) {
                $this->logger->warning("[SvgConceptStrategy] upload failed, fallback to data uri: {$e->getMessage()}");
                $url = 'data:image/svg+xml;base64,' . base64_encode($svg);
            }
        } else {
            $url = 'data:image/svg+xml;base64,' . base64_encode($svg);
        }

        return new ImageResult(
            source: 'svg',
            url: $url,
            originalUrl: $url,
            alt: "示意图：{$kw}",
            attribution: 'Generated by DashScope',
            mime: 'image/svg+xml',
            raw: mb_substr($svg, 0, 200),
        );
    }

    private function buildPrompt(string $keyword, string $context): string
    {
        $ctx = $context !== '' ? "\n上下文：{$context}" : '';
        return <<<PROMPT
请根据以下概念生成一张简洁的 SVG 示意图，用于嵌入技术文章作为插图。

概念关键词：{$keyword}{$ctx}

约束：
1. 画布大小 800x400，viewBox="0 0 800 400"
2. 使用简单几何图形（矩形、圆、箭头、连线）配合少量中文/英文标签
3. 颜色风格：柔和的蓝紫色系（如 #4f6cf7 / #7e3cf2 / #12b981）
4. **只输出 <svg>...</svg> 代码**，不要 <?xml 声明，不要注释，不要 <script>
PROMPT;
    }

    /** 抽取 <svg>...</svg> 块；同时移除 script 标签防止 XSS。 */
    private function extractSvg(string $raw): string
    {
        if (! preg_match('/<svg[\s\S]*?<\/svg>/i', $raw, $m)) {
            return '';
        }
        $svg = $m[0];
        // 清洗 script / on* handlers
        $svg = preg_replace('/<script[\s\S]*?<\/script>/i', '', $svg) ?? $svg;
        $svg = preg_replace('/\son\w+="[^"]*"/i', '', $svg) ?? $svg;
        $svg = preg_replace('/\son\w+=\'[^\']*\'/i', '', $svg) ?? $svg;
        return trim($svg);
    }
}
